#!/bin/bash 
touch '\*\\'\''Best School'\''\\*$?********:)' # echo "Best School" >> '\*\\'\''Best School'\''\\*$?********:)' # adds "Best School" to file
echo "" >> '\*\\'\''Best School'\''\\*$?********:)' 
